### ISSUE TITLE
Missing Actor And Director Comment Models and Controllers

### ISSUE THREAD

**Issue by kez96** [DMU-CTEC2902/LC-TeamFlash#2]
The Actor Comment and Director Comment Models and Controllers are not included when pulling the master branch from GitHub. Visual Studio says they should be there but the files themselves are missing. They are also missing when browsing through the file explorer on GitHub.

**Comment by zeedurwesh** [comment]
try downloading it from my dev branch.
thanks


Sent from my Samsung Galaxy smartphone.<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Kieran Edwards <notifications@github.com> </div><div>Date: 10/05/2016  11:29  (GMT+00:00) </div><div>To: DMU-CTEC2902/LC-TeamFlash <LC-TeamFlash@noreply.github.com> </div><div>Subject: [DMU-CTEC2902/LC-TeamFlash] Missing Actor And Director Comment Models and Controllers (#2) </div><div>
</div>
The Actor Comment and Director Comment Models and Controllers are not included when pulling the master branch from GitHub. Visual Studio says they should be there but the files themselves are missing. They are also missing when browsing through the file explorer on GitHub.

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/DMU-CTEC2902/LC-TeamFlash/issues/2

**Comment by kez96** [comment]
Ah okay, will do. Thank you
